version: "3.8"

services:
  json_server:
    image: clue/json-server
    ports:
      - 8888:80
    volumes:
      - ./db.json:/data/db.json
  app:
    container_name: app-prod-c
    image: app-prod-i
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "80:3000"
    environment:
     - REACT_APP_URL_PROD=http://localhost:8888/